apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-app
  namespace: argocd
spec:
  destination:
    namespace: quarkus-ns
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: 'https://redhat-developer.github.io/redhat-helm-charts'
    chart: quarkus
    targetRevision: 0.0.3
    helm:
      releaseName: quarkus-release
      valueFiles:
      - $Infra/value/values.yaml
  - repoURL: 'https://github.com/younesELouafi/helm-argo'
    ref: Infra    
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
