apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonar-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/younesELouafi/helm-argo'
    path: Infra/sonar
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sonar-ns
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
